# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2019-01-14 17:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0002_auto_20190114_1643'),
    ]

    operations = [
        migrations.CreateModel(
            name='siteBanner',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=100, null=True)),
                ('image', models.ImageField(null=True, upload_to='images/%m/')),
                ('public', models.BooleanField(verbose_name='make public')),
                ('uploaded_at', models.DateField(auto_now=True)),
                ('description', models.CharField(max_length=255, null=True)),
            ],
            options={
                'verbose_name': 'Site Banner',
            },
        ),
    ]
