# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2019-07-11 17:21
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0005_generalproduct_gp_description'),
    ]

    operations = [
        migrations.CreateModel(
            name='MobiDetail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('m_type', models.CharField(choices=[('SM', 'Smart Phone'), ('SP', 'Simple Phone'), ('TA', 'Tablet')], default='SM', max_length=2, verbose_name='type of mobile device')),
                ('m_os', models.CharField(max_length=60, verbose_name='OS')),
                ('m_cpu', models.CharField(max_length=60, verbose_name='CPU size')),
                ('m_size', models.CharField(max_length=60, verbose_name='size of item')),
                ('m_size_num', models.DecimalField(decimal_places=1, max_digits=3, verbose_name='size')),
                ('m_int_memory', models.CharField(max_length=60, verbose_name='internal memory')),
                ('m_storage', models.CharField(max_length=60, verbose_name='storage size')),
                ('m_storage_num', models.IntegerField(verbose_name='Storage Size')),
                ('m_has_wifi', models.BooleanField(default=True, verbose_name='Wifi Capable')),
                ('m_has_bluetooth', models.BooleanField(default=True, verbose_name='bluetooth Capable')),
                ('m_has_gps', models.BooleanField(default=True, verbose_name='GPS Capable')),
                ('m_simcard', models.CharField(choices=[('S', 'Single Sim'), ('D', 'Dual Sim')], default='S', max_length=1, verbose_name='sim type')),
                ('m_camera_px', models.IntegerField(verbose_name='camera pixels')),
                ('m_product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='store.GeneralProduct')),
            ],
            options={
                'ordering': ['m_type'],
                'verbose_name': 'Mobile Detail',
            },
        ),
    ]
